[paths]
samples = samples/

[song]
bpm = 120
ticks = 4
patterns = 112244334435

[samples]
bass = Bass(3).wav
bass1 = Bass(4).wav
bassdrum = 909_bass_drum.wav
clap = 909_clap.wav
crash = 909_crash.wav
hi_tom = 909_hi_tom.wav
hh = 909_hihat_closed.wav
hihat_open = 909_hihat_open.wav
low_tom = 909_low_tom.wav
mid_tom = 909_mid_tom.wav
ride = 909_ride.wav
rimshot = 909_rimshot.wav
snare1 = biab_sn_3.wav
snaredrum = 909_snare_drum.wav

[pattern.1]
bassdrum = x...x...x...x...

[pattern.2]
bassdrum = x...x...x...x...
clap = x.......x.......

[pattern.3]
bass = x.x.....xx.x....
bassdrum = x...x...x...x...
clap = x.......x.......
hh = xxxx..xxxx..xxxx
low_tom = x.x.....xx.x....

[pattern.4]
bass1 = x.x.....xx.x....
bassdrum = x...x...x...x...
clap = x.......x.......
hh = ................

[pattern.5]
bass = x.x.....xx.x....
clap = x.......x.......

