[paths]
samples = samples/

[song]
bpm = 124
ticks = 4
patterns = 1

[samples]
bassdrum = 909_bass_drum.wav
clap = 909_clap.wav
crash = 909_crash.wav
hi_tom = 909_hi_tom.wav
hihat_closed = 909_hihat_closed.wav
hihat_open = 909_hihat_open.wav
low_tom = 909_low_tom.wav
mid_tom = 909_mid_tom.wav
ride = 909_ride.wav
rimshot = 909_rimshot.wav
snaredrum = 909_snare_drum.wav

[pattern.1]
bassdrum = x...x...x...x...

